version: '3.9'

services:
  task-submission-service:
    depends_on:
      - postgres
      - rabbitmq
    build:
      context: ./task-submission-service
      dockerfile: Dockerfile
    container_name: task-submission-service
    environment:
      NODE_ENV: production
      CLUSTER_SIZE: 1

      RABBITMQ_HOST: ${RABBITMQ_HOST:-rabbitmq}
      RABBITMQ_PORT: ${RABBITMQ_PORT:-5672}
      RABBITMQ_USER: ${RABBITMQ_USER:-guest}
      RABBITMQ_PASS: ${RABBITMQ_PASS:-guest}

      POSTGRES_HOST: ${POSTGRES_HOST:-postgres}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-licence_market}

    ports:
      - "3000:${SUBMISSION_SERVICE_PORT}"
    restart: unless-stopped
    networks:
      - task-queue-project-network

  task-worker-service:
    depends_on:
      - rabbitmq
      - task-submission-service
    build:
      context: ./task-worker-service
      dockerfile: Dockerfile
    container_name: task-worker-service
    environment:
      NODE_ENV: production
      CLUSTER_SIZE: 1

      RABBITMQ_HOST: ${RABBITMQ_HOST:-rabbitmq}
      RABBITMQ_PORT: ${RABBITMQ_PORT:-5672}
      RABBITMQ_USER: ${RABBITMQ_USER:-guest}
      RABBITMQ_PASS: ${RABBITMQ_PASS:-guest}
    networks:
      - task-queue-project-network

  rabbitmq:
    image: rabbitmq:3
    container_name: rabbitmq
    ports:
      - "5672:${RABBITMQ_PORT}"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:-guest}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS:-guest}
    networks:
      - task-queue-project-network

  postgres:
    image: postgres:17.0
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_HOST: ${POSTGRES_HOST:-localhost}
      POSTGRES_DB: ${POSTGRES_DB:-licence_market}
      PGDATA: /data/postgres
    volumes:
      - postgres_16:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - task-queue-project-network

volumes:
  rabbitmq_data:
  postgres_16:

networks:
  task-queue-project-network:
    driver: bridge